spring:
  application:
    name: itau-code-challange-starter-kit
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:core-banking-consumer}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

dynamodb:
  endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}
  region: ${DYNAMODB_REGION:us-east-1}
  table-name: ${DYNAMODB_TABLE:core_banking}

account-created:
  topic-name: ${ACCOUNT_CREATED_TOPIC:conta-bancaria-criada}

app:
  default-currency: BRL
  response-timezone: America/Sao_Paulo

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  pattern:
    console: '{"timestamp":"%d{ISO8601}","level":"%p","logger":"%c","thread":"%t","msg":"%m","exception":"%replace(%ex){\"\n\":\"\\n\"}"}%n'
